services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nosql_project
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "8001:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
